/*
 * SIL - SNOBOL Interpretation Language
 * Copyright (c) 2021, Michael D Henderson
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package sil

// The system-dependent group of S4D58 7.5, less INIT and ENDEX, which
// are in macros.go with the rest of the vertical slice.
//
// Two of them ask the machine's environment for something -- the time
// and the date -- and go through the Host. The other three are the
// external-function group, and this machine has no external
// functions: 7.1 footnote 4 says LINK, LOAD and UNLOAD are to be
// implemented or not implemented together, and each of their sections
// says what not implementing it means. Those alternatives are what is
// here, stated rather than hidden.

// Undefined is the label 7.1 sends an unimplemented LOAD to, and 6.57
// note 2 explains why it is not INTR10: "the built-in function LOAD
// will not be available, and an error comment should be generated by
// branching to UNDF". It is a program error, not an error in the
// implementation of the macro language.
const Undefined = "UNDF"

// undefined transfers to UNDF, the way interrupt transfers to INTR10.
func (s *VM) undefined(format string, args ...any) error {
	return s.transfer(Undefined, format, args...)
}

// MSTIME (get millisecond time) is used to get the millisecond time.
//
// Data Altered:
//
//	DESCR TIME,0,0
//
// Programming Notes:
//  1. The origin with respect to which the time is obtained is not
//     important. The SNOBOL4 system deals only with differences in
//     times.
//  2. The time units should be milliseconds, but accuracy is not
//     critical.
//  3. MSTIME is used in program tracing, the SNOBOL4 TIME function,
//     and in statistics printed upon termination of a SNOBOL4 run.
//  4. It is not critically important that MSTIME be implemented as
//     such. If it is not, the address field of DESCR should be set to
//     zero also.
//
// Note 4 is why a host with no clock is not a deviation: returning
// zero is the documented answer, and it is what WriterHost gives, so a
// test run is reproducible.
//
// S4D58.PDF: 6.71
func (s *VM) MSTIME(descr int) {
	s.Core[descr] = Cell{Kind: Data, A: s.Host.Time()}
}

// DATE (get date) is used to obtain the current date. A character
// representation of the current date is placed in BUFFER.
//
// Data Altered:
//
//	SPEC   BUFFER,0,0,0,L
//	BUFFER C1...CL
//
// Programming Notes:
//  1. The choice of representation for the date is not important so
//     far as the source language is concerned. Thus April 1, 1981,
//     04/01/81, 4:1:81 and 81.092 are all acceptable.
//  2. BUFFER is local to DATE and its old contents may be overwritten
//     by a subsequent use of DATE.
//  3. DATE is used only in the SNOBOL4 DATE function.
//  4. Implementation of DATE, as such, is not essential. In this case,
//     DATE should set the length of SPEC to zero and do nothing else.
//
// Note 4 is the case where the host has no calendar, and it is drawn
// exactly: only the length of SPEC changes, as in LOCSP's null string.
// Note 2 gives DATE its own buffer, as 6.49 note 2 gives INTSPC one;
// see VM.buffer.
//
// S4D58.PDF: 6.22
func (s *VM) DATE(spec int) {
	text := s.Host.Date()
	if len(text) == 0 {
		*s.lengthOf(spec) = 0
		return
	}
	at := s.buffer(&s.dateBuf, len(text))
	s.putChars(at, text)
	s.putSpecifier(spec, at, 0, 0, 0, len(text))
}

// LOAD (load external function) is used to load an external function.
// C11...C1L1 is the name of the external function to be loaded from a
// library. C21...C2L2 is the name of the library. A3 is the address of
// the entry point. If the external function is loaded, transfer is to
// SLOC. Otherwise transfer is to FLOC.
//
// Data Input:
//
//	SPEC1 A1,O1,L1
//	SPEC2 A2,O2,L2
//	A1+O1 C11...C1L1
//	A2+O2 C21...C2L2
//
// Data Altered:
//
//	DESCR A3
//
// Programming Notes:
//  1. LOAD is a system-dependent operation.
//  2. LOAD need not be implemented as such. If it is not, the built-in
//     function LOAD will not be available, and an error comment should
//     be generated by branching to UNDF.
//  3. On the IBM System/360, LOAD uses the OS macro LOAD to bring an
//     external function from the library whose DDNAME is specified by
//     C21...C2L2.
//  4. See also LINK and UNLOAD.
//
// This is note 2's alternative, which 7.1 lists as "branch to UNDF"
// with the feature disabled as external functions. There is nothing
// for a Go host to load: an external function on this machine would be
// a machine-language subroutine reached through MLINK, and MLINK is
// empty because this machine has none. Note that FLOC is not the right
// arm -- a load that failed is a different thing from a system that
// cannot load, and 6.57 note 2 names UNDF for the second.
//
// S4D58.PDF: 6.57
func (s *VM) LOAD(descr, spec1, spec2, floc, sloc int) error {
	return s.undefined("LOAD: this machine has no external functions")
}

// LINK (link to external function) is used to link to an external
// function. A2 is a pointer to an argument list of N descriptors. A4
// is the address of the external function to be called. V1 is the data
// type expected for the resulting value. The returned value is placed
// in DESCR1. If the external function signals failure, transfer is to
// FLOC. Otherwise transfer is to SLOC.
//
// Data Input:
//
//	DESCR1 V1
//	DESCR2 A2
//	DESCR3 N
//	DESCR4 A4
//
// Data Altered:
//
//	DESCR1 A,F,V
//
// Programming Notes:
//  1. LINK is a system-dependent operation.
//  2. LINK need not be implemented if LOAD is not. In this case, LINK
//     should branch to INTR10.
//  3. See also LOAD and UNLOAD.
//
// Note 2's alternative, and 7.1 lists it the same way. INTR10 rather
// than UNDF because nothing can reach a LINK without a LOAD having
// succeeded first: getting here at all is an error in the
// implementation of the macro language, which is what 7.3 says INTR10
// is for.
//
// S4D58.PDF: 6.55
func (s *VM) LINK(descr1, descr2, descr3, descr4, floc, sloc int) error {
	return s.interrupt("LINK: this machine has no external functions")
}

// UNLOAD (unload external function) is used to unload an external
// function. C1...CL represents the name of the function that is to be
// unloaded.
//
// Data Input:
//
//	SPEC A,O,L
//	A+O  C1...CL
//
// Programming Notes:
//  1. UNLOAD is a system-dependent operation.
//  2. UNLOAD need not be implemented as such. If it is not, it should
//     perform no operation, since the SNOBOL function UNLOAD, which
//     uses the macro UNLOAD, has a valid use in undefining existing,
//     but non-external, functions.
//  3. UNLOAD should do nothing if the function C1...CL is not a LOADed
//     function.
//  4. See also LOAD and LINK.
//
// Note 2 does not merely permit the no-operation, it requires it: the
// source-language UNLOAD works on ordinary defined functions too, and
// the macro is called on the way through. Note 3 says the same thing
// from the other side -- a name that was never LOADed is not an error.
// With no external functions, no name ever was.
//
// S4D58.PDF: 6.126
func (s *VM) UNLOAD(spec int) {}
